In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import StandardScaler

In [2]:
PROJECT_ROOT = Path.cwd().parent
train_path = PROJECT_ROOT / "all_datasets" / "breast_cancer_dataset" / "data.csv"
df = pd.read_csv(train_path)

In [3]:
feature_cols = [c for c in df.columns if c not in {"id", "diagnosis", "Unnamed: 32"}]
X = df[feature_cols]

In [4]:
# Compare raw Euclidean distance with distance after standardization.
raw = pairwise_distances(X.iloc[:5], metric="euclidean")
X_scaled = StandardScaler().fit_transform(X)
scaled = pairwise_distances(X_scaled[:5], metric="euclidean")

In [5]:
np.set_printoptions(precision=2, suppress=True)
print("Raw distances among first five rows:\n", raw)
print("\nScaled distances among first five rows:\n", scaled)

Raw distances among first five rows:
 [[   0.    341.73  376.46 1584.31  538.02]
 [ 341.73    0.    276.78 1679.24  382.8 ]
 [ 376.46  276.78    0.   1407.17  164.15]
 [1584.31 1679.24 1407.17    0.   1362.11]
 [ 538.02  382.8   164.15 1362.11    0.  ]]

Scaled distances among first five rows:
 [[ 0.   10.32  6.78 10.47  8.67]
 [10.32  0.    5.03 16.25  4.38]
 [ 6.78  5.03  0.   12.84  4.46]
 [10.47 16.25 12.84  0.   15.38]
 [ 8.67  4.38  4.46 15.38  0.  ]]


In [6]:
# Cosine similarity answers a different question: direction rather than magnitude.
cosine_distance = pairwise_distances(X_scaled[:5], metric="cosine")
print("\nCosine similarities:\n", 1 - cosine_distance)


Cosine similarities:
 [[ 1.    0.31  0.81  0.67  0.59]
 [ 0.31  1.    0.61 -0.29  0.69]
 [ 0.81  0.61  1.    0.4   0.72]
 [ 0.67 -0.29  0.4   1.   -0.04]
 [ 0.59  0.69  0.72 -0.04  1.  ]]
